/********************************************************************************
** Form generated from reading UI file 'GLMark.ui'
**
** Created by: Qt User Interface Compiler version 5.5.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_GLMARK_H
#define UI_GLMARK_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QListWidget>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_GLMark
{
public:
    QWidget *centralWidget;
    QTabWidget *tabWidget;
    QWidget *tab_general_test;
    QPushButton *pushButtonGeneralTest;
    QLabel *label_conf;
    QGroupBox *group_lay;
    QLabel *border_lay;
    QLabel *label_lay;
    QGroupBox *size_lay;
    QLabel *x_lay;
    QSpinBox *row_spin;
    QSpinBox *column_spin;
    QGroupBox *group_pix;
    QLabel *label_pix;
    QLabel *border_pix;
    QGroupBox *radios_pix;
    QRadioButton *radio_rgb32;
    QRadioButton *radio_yuv420;
    QRadioButton *radio_yv12;
    QGroupBox *group_video;
    QLabel *label_video;
    QLabel *border_video;
    QGroupBox *radios_video;
    QRadioButton *radio_CIF;
    QRadioButton *radio_D1;
    QRadioButton *radio_720p;
    QRadioButton *radio_1080p;
    QGroupBox *group_screen;
    QLabel *label_screen_resolution;
    QLabel *border_screen;
    QLabel *label_screen_frequncy;
    QComboBox *comboBoxResolution;
    QComboBox *comboBoxFrequency;
    QPushButton *pushButtonSaveRenderingSample;
    QWidget *tab_unit_test;
    QPushButton *pushButtonMultipleWindows;
    QGroupBox *groupBox;
    QLabel *label_multiple_windows;
    QCheckBox *checkBox2x2;
    QCheckBox *checkBox4x4;
    QCheckBox *checkBox6x6;
    QCheckBox *checkBox8x8;
    QLabel *label_2;
    QGroupBox *groupBox_2;
    QLabel *label_multiple_windows_2;
    QCheckBox *checkBox256x256;
    QCheckBox *checkBoxCIF;
    QCheckBox *checkBox512x512;
    QCheckBox *checkBoxD1;
    QCheckBox *checkBox720p;
    QCheckBox *checkBox1080p;
    QLabel *label;
    QPushButton *pushButtonTextureUpload;
    QPushButton *pushButtonDifferentResolution;
    QGroupBox *groupBox_3;
    QLabel *label_multiple_windows_3;
    QCheckBox *checkBox256x256DifferentResolution;
    QCheckBox *checkBoxCIFDifferentResolution;
    QCheckBox *checkBox512x512DifferentResolution;
    QCheckBox *checkBoxD1DifferentResolution;
    QCheckBox *checkBox720pDifferentResolution;
    QCheckBox *checkBox1080pDifferentResolution;
    QLabel *label_3;
    QGroupBox *groupBox_4;
    QLabel *label_multiple_windows_4;
    QCheckBox *checkBoxRGB32;
    QCheckBox *checkBoxYUV420;
    QCheckBox *checkBoxYV12;
    QLabel *label_4;
    QPushButton *pushButtonDifferentFormat;
    QGroupBox *groupBox_5;
    QLabel *label_multiple_windows_5;
    QCheckBox *checkBoxSingleProcess;
    QCheckBox *checkBoxMultipleProcesses;
    QLabel *label_5;
    QPushButton *pushButtonMultipleMonitors;
    QPushButton *pushButtonRunAll;
    QWidget *tab_test_configuration;
    QLabel *label_conf_2;
    QPushButton *pushButtonAdd;
    QListWidget *listWidget;
    QPushButton *pushButtonRunTestConf;
    QPushButton *pushButtonSaveTestConf;
    QPushButton *pushButtonDelete;
    QPushButton *pushButtonEdit;
    QPushButton *pushButtonUp;
    QPushButton *pushButtonDown;
    QTabWidget *tabWidgetType;
    QWidget *tab_2;
    QGroupBox *group_mode;
    QLabel *label_mode;
    QLabel *border_mode;
    QGroupBox *radios_mode;
    QRadioButton *radio_mode_video;
    QRadioButton *radio_mode_texture;
    QRadioButton *radio_mode_multiple;
    QGroupBox *group_layout;
    QLabel *border_layout;
    QLabel *label_layout;
    QGroupBox *size_layout;
    QLabel *x_layout;
    QSpinBox *row_spin_test;
    QSpinBox *column_spin_test;
    QGroupBox *group_pix_test;
    QLabel *label_pix_test;
    QLabel *border_pix_test;
    QGroupBox *radios_pix_test;
    QRadioButton *radio_rgb32_test;
    QRadioButton *radio_yuv420_test;
    QRadioButton *radio_yv12_test;
    QGroupBox *group_video_test;
    QLabel *label_video_test;
    QLabel *border_video_test;
    QGroupBox *radios_video_test;
    QRadioButton *radio_CIF_test;
    QRadioButton *radio_D1_test;
    QRadioButton *radio_720p_test;
    QRadioButton *radio_1080p_test;
    QRadioButton *radio_512x512_test;
    QRadioButton *radio_256x256_test;
    QGroupBox *group_screen_test;
    QLabel *label_screen_resolution_2;
    QLabel *border_screen_test;
    QLabel *label_screen_frequncy_2;
    QComboBox *comboBoxTestResolution;
    QComboBox *comboBoxTestFrequency;
    QGroupBox *group_process;
    QLabel *label_process;
    QLabel *border_process;
    QGroupBox *radios_process;
    QRadioButton *radio_process_single;
    QRadioButton *radio_process_one;
    QGroupBox *group_time;
    QLabel *border_time;
    QLabel *label_time;
    QGroupBox *size_time;
    QLabel *s_time;
    QSpinBox *time_spin_test;
    QWidget *tab_3;
    QGroupBox *group_lay_decode_2;
    QLabel *border_lay_decode_2;
    QLabel *label_lay_decode_2;
    QGroupBox *size_lay_decode_2;
    QLabel *x_lay_decode_2;
    QSpinBox *row_spin_decode_test;
    QSpinBox *column_spin_decode_test;
    QGroupBox *group_flag_2;
    QLabel *label_flag_2;
    QLabel *border_flag_2;
    QGroupBox *checkBoxes_flag_3;
    QCheckBox *checkBoxRenderingVideo_test;
    QCheckBox *checkBoxDecodeVideo_test;
    QCheckBox *checkBoxDownScaling_test;
    QGroupBox *group_thread_number_2;
    QLabel *label_thread_number_2;
    QLabel *border_thread_number_2;
    QGroupBox *spin_border_2;
    QSpinBox *spin_thread_number_test;
    QGroupBox *group_timing_control_2;
    QLabel *label_timing_control_4;
    QLabel *border_timing_control_2;
    QLabel *label_rate_2;
    QDoubleSpinBox *doubleSpinBox_test;
    QGroupBox *checkBoxes_flag_4;
    QCheckBox *checkBoxTimingControlEnable_test;
    QGroupBox *group_time_2;
    QLabel *border_time_2;
    QLabel *label_time_2;
    QGroupBox *size_time_2;
    QLabel *s_time_2;
    QSpinBox *time_spin_test_decode;
    QWidget *tab_decode_sample;
    QPushButton *pushButtonRunDecodeSample;
    QLabel *label_conf_decode;
    QGroupBox *group_lay_decode;
    QLabel *border_lay_decode;
    QLabel *label_lay_decode;
    QGroupBox *size_lay_decode;
    QLabel *x_lay_decode;
    QSpinBox *row_spin_decode;
    QSpinBox *column_spin_decode;
    QGroupBox *group_flag;
    QLabel *label_flag;
    QLabel *border_flag;
    QGroupBox *checkBoxes_flag;
    QCheckBox *checkBoxRenderingVideo;
    QCheckBox *checkBoxDecodeVideo;
    QCheckBox *checkBoxDownScaling;
    QGroupBox *group_thread_number;
    QLabel *label_thread_number;
    QLabel *border_thread_number;
    QGroupBox *spin_border;
    QSpinBox *spin_thread_number;
    QGroupBox *group_timing_control;
    QLabel *label_timing_control_3;
    QLabel *border_timing_control;
    QLabel *label_rate;
    QDoubleSpinBox *doubleSpinBox;
    QGroupBox *checkBoxes_flag_2;
    QCheckBox *checkBoxTimingControlEnable;
    QPushButton *pushButtonSaveDecodeSample;
    QWidget *tab;
    QGroupBox *groupBox_db;
    QLabel *label_multiple_windows_db;
    QCheckBox *checkBox2x2_db;
    QCheckBox *checkBox4x4_db;
    QCheckBox *checkBox6x6_db;
    QCheckBox *checkBox8x8_db;
    QLabel *label_8;
    QCheckBox *checkBox1x1_db;
    QPushButton *pushButtonMultipleWindows_db;
    QWidget *tab_general_options;
    QLabel *label_6;
    QLineEdit *lineEditExportReport;
    QPushButton *pushButtonExportReport;
    QLabel *label_7;
    QLineEdit *lineEditSaveScreenshot;
    QPushButton *pushButtonSaveScreenshot;
    QPushButton *pushButtonSaveGeneralOptions;

    void setupUi(QMainWindow *GLMark)
    {
        if (GLMark->objectName().isEmpty())
            GLMark->setObjectName(QStringLiteral("GLMark"));
        GLMark->resize(800, 630);
        GLMark->setMinimumSize(QSize(800, 630));
        centralWidget = new QWidget(GLMark);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        tabWidget = new QTabWidget(centralWidget);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setGeometry(QRect(10, 10, 780, 610));
        tabWidget->setMaximumSize(QSize(16777215, 16777215));
        tab_general_test = new QWidget();
        tab_general_test->setObjectName(QStringLiteral("tab_general_test"));
        pushButtonGeneralTest = new QPushButton(tab_general_test);
        pushButtonGeneralTest->setObjectName(QStringLiteral("pushButtonGeneralTest"));
        pushButtonGeneralTest->setGeometry(QRect(610, 20, 140, 40));
        label_conf = new QLabel(tab_general_test);
        label_conf->setObjectName(QStringLiteral("label_conf"));
        label_conf->setGeometry(QRect(240, 20, 141, 40));
        QFont font;
        font.setPointSize(15);
        font.setUnderline(true);
        label_conf->setFont(font);
        label_conf->setFrameShape(QFrame::NoFrame);
        label_conf->setFrameShadow(QFrame::Sunken);
        label_conf->setLineWidth(1);
        label_conf->setTextFormat(Qt::AutoText);
        label_conf->setIndent(10);
        group_lay = new QGroupBox(tab_general_test);
        group_lay->setObjectName(QStringLiteral("group_lay"));
        group_lay->setGeometry(QRect(30, 85, 710, 51));
        border_lay = new QLabel(group_lay);
        border_lay->setObjectName(QStringLiteral("border_lay"));
        border_lay->setGeometry(QRect(0, 0, 710, 51));
        border_lay->setFrameShape(QFrame::Box);
        border_lay->setFrameShadow(QFrame::Sunken);
        label_lay = new QLabel(group_lay);
        label_lay->setObjectName(QStringLiteral("label_lay"));
        label_lay->setGeometry(QRect(2, 5, 80, 40));
        QFont font1;
        font1.setPointSize(14);
        font1.setUnderline(false);
        label_lay->setFont(font1);
        label_lay->setFrameShape(QFrame::NoFrame);
        label_lay->setFrameShadow(QFrame::Sunken);
        label_lay->setLineWidth(1);
        label_lay->setTextFormat(Qt::AutoText);
        label_lay->setIndent(10);
        size_lay = new QGroupBox(group_lay);
        size_lay->setObjectName(QStringLiteral("size_lay"));
        size_lay->setGeometry(QRect(180, 4, 121, 41));
        x_lay = new QLabel(size_lay);
        x_lay->setObjectName(QStringLiteral("x_lay"));
        x_lay->setGeometry(QRect(55, 13, 16, 16));
        QFont font2;
        font2.setPointSize(14);
        x_lay->setFont(font2);
        row_spin = new QSpinBox(size_lay);
        row_spin->setObjectName(QStringLiteral("row_spin"));
        row_spin->setGeometry(QRect(3, 5, 45, 31));
        row_spin->setMinimum(1);
        row_spin->setMaximum(8);
        column_spin = new QSpinBox(size_lay);
        column_spin->setObjectName(QStringLiteral("column_spin"));
        column_spin->setGeometry(QRect(72, 5, 45, 31));
        column_spin->setMinimum(1);
        column_spin->setMaximum(8);
        group_pix = new QGroupBox(tab_general_test);
        group_pix->setObjectName(QStringLiteral("group_pix"));
        group_pix->setGeometry(QRect(30, 156, 710, 51));
        label_pix = new QLabel(group_pix);
        label_pix->setObjectName(QStringLiteral("label_pix"));
        label_pix->setGeometry(QRect(0, 5, 125, 40));
        label_pix->setFont(font1);
        label_pix->setFrameShape(QFrame::NoFrame);
        label_pix->setFrameShadow(QFrame::Sunken);
        label_pix->setLineWidth(1);
        label_pix->setTextFormat(Qt::AutoText);
        label_pix->setIndent(10);
        border_pix = new QLabel(group_pix);
        border_pix->setObjectName(QStringLiteral("border_pix"));
        border_pix->setGeometry(QRect(0, 0, 710, 51));
        border_pix->setFrameShape(QFrame::Box);
        border_pix->setFrameShadow(QFrame::Sunken);
        radios_pix = new QGroupBox(group_pix);
        radios_pix->setObjectName(QStringLiteral("radios_pix"));
        radios_pix->setGeometry(QRect(180, 5, 245, 41));
        radio_rgb32 = new QRadioButton(radios_pix);
        radio_rgb32->setObjectName(QStringLiteral("radio_rgb32"));
        radio_rgb32->setGeometry(QRect(3, 10, 72, 22));
        radio_yuv420 = new QRadioButton(radios_pix);
        radio_yuv420->setObjectName(QStringLiteral("radio_yuv420"));
        radio_yuv420->setGeometry(QRect(84, 10, 82, 22));
        radio_yv12 = new QRadioButton(radios_pix);
        radio_yv12->setObjectName(QStringLiteral("radio_yv12"));
        radio_yv12->setGeometry(QRect(173, 10, 63, 22));
        radio_yv12->setChecked(true);
        group_video = new QGroupBox(tab_general_test);
        group_video->setObjectName(QStringLiteral("group_video"));
        group_video->setGeometry(QRect(30, 226, 710, 51));
        label_video = new QLabel(group_video);
        label_video->setObjectName(QStringLiteral("label_video"));
        label_video->setGeometry(QRect(0, 5, 170, 40));
        label_video->setFont(font1);
        label_video->setFrameShape(QFrame::NoFrame);
        label_video->setFrameShadow(QFrame::Sunken);
        label_video->setLineWidth(1);
        label_video->setTextFormat(Qt::AutoText);
        label_video->setIndent(10);
        border_video = new QLabel(group_video);
        border_video->setObjectName(QStringLiteral("border_video"));
        border_video->setGeometry(QRect(0, 0, 710, 51));
        border_video->setFrameShape(QFrame::Box);
        border_video->setFrameShadow(QFrame::Sunken);
        radios_video = new QGroupBox(group_video);
        radios_video->setObjectName(QStringLiteral("radios_video"));
        radios_video->setGeometry(QRect(180, 5, 256, 41));
        radio_CIF = new QRadioButton(radios_video);
        radio_CIF->setObjectName(QStringLiteral("radio_CIF"));
        radio_CIF->setGeometry(QRect(2, 10, 50, 22));
        radio_D1 = new QRadioButton(radios_video);
        radio_D1->setObjectName(QStringLiteral("radio_D1"));
        radio_D1->setGeometry(QRect(56, 10, 50, 22));
        radio_720p = new QRadioButton(radios_video);
        radio_720p->setObjectName(QStringLiteral("radio_720p"));
        radio_720p->setGeometry(QRect(107, 10, 60, 22));
        radio_1080p = new QRadioButton(radios_video);
        radio_1080p->setObjectName(QStringLiteral("radio_1080p"));
        radio_1080p->setGeometry(QRect(172, 10, 70, 22));
        radio_1080p->setChecked(true);
        group_screen = new QGroupBox(tab_general_test);
        group_screen->setObjectName(QStringLiteral("group_screen"));
        group_screen->setGeometry(QRect(30, 300, 710, 90));
        label_screen_resolution = new QLabel(group_screen);
        label_screen_resolution->setObjectName(QStringLiteral("label_screen_resolution"));
        label_screen_resolution->setGeometry(QRect(0, 5, 170, 40));
        label_screen_resolution->setFont(font1);
        label_screen_resolution->setFrameShape(QFrame::NoFrame);
        label_screen_resolution->setFrameShadow(QFrame::Sunken);
        label_screen_resolution->setLineWidth(1);
        label_screen_resolution->setTextFormat(Qt::AutoText);
        label_screen_resolution->setIndent(10);
        border_screen = new QLabel(group_screen);
        border_screen->setObjectName(QStringLiteral("border_screen"));
        border_screen->setGeometry(QRect(0, 0, 710, 90));
        border_screen->setFrameShape(QFrame::Box);
        border_screen->setFrameShadow(QFrame::Sunken);
        label_screen_frequncy = new QLabel(group_screen);
        label_screen_frequncy->setObjectName(QStringLiteral("label_screen_frequncy"));
        label_screen_frequncy->setGeometry(QRect(55, 45, 105, 40));
        label_screen_frequncy->setFont(font1);
        label_screen_frequncy->setFrameShape(QFrame::NoFrame);
        label_screen_frequncy->setFrameShadow(QFrame::Sunken);
        label_screen_frequncy->setLineWidth(1);
        label_screen_frequncy->setTextFormat(Qt::AutoText);
        label_screen_frequncy->setIndent(10);
        comboBoxResolution = new QComboBox(group_screen);
        comboBoxResolution->setObjectName(QStringLiteral("comboBoxResolution"));
        comboBoxResolution->setGeometry(QRect(180, 15, 120, 22));
        comboBoxFrequency = new QComboBox(group_screen);
        comboBoxFrequency->setObjectName(QStringLiteral("comboBoxFrequency"));
        comboBoxFrequency->setGeometry(QRect(180, 55, 69, 22));
        pushButtonSaveRenderingSample = new QPushButton(tab_general_test);
        pushButtonSaveRenderingSample->setObjectName(QStringLiteral("pushButtonSaveRenderingSample"));
        pushButtonSaveRenderingSample->setGeometry(QRect(320, 510, 140, 40));
        tabWidget->addTab(tab_general_test, QString());
        tab_unit_test = new QWidget();
        tab_unit_test->setObjectName(QStringLiteral("tab_unit_test"));
        pushButtonMultipleWindows = new QPushButton(tab_unit_test);
        pushButtonMultipleWindows->setObjectName(QStringLiteral("pushButtonMultipleWindows"));
        pushButtonMultipleWindows->setGeometry(QRect(610, 50, 140, 40));
        groupBox = new QGroupBox(tab_unit_test);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(20, 30, 561, 80));
        label_multiple_windows = new QLabel(groupBox);
        label_multiple_windows->setObjectName(QStringLiteral("label_multiple_windows"));
        label_multiple_windows->setGeometry(QRect(0, 0, 561, 80));
        QFont font3;
        font3.setPointSize(11);
        label_multiple_windows->setFont(font3);
        label_multiple_windows->setFrameShape(QFrame::Box);
        label_multiple_windows->setFrameShadow(QFrame::Sunken);
        label_multiple_windows->setLineWidth(1);
        label_multiple_windows->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        label_multiple_windows->setMargin(5);
        label_multiple_windows->setIndent(10);
        checkBox2x2 = new QCheckBox(groupBox);
        checkBox2x2->setObjectName(QStringLiteral("checkBox2x2"));
        checkBox2x2->setGeometry(QRect(20, 50, 60, 22));
        checkBox2x2->setChecked(true);
        checkBox4x4 = new QCheckBox(groupBox);
        checkBox4x4->setObjectName(QStringLiteral("checkBox4x4"));
        checkBox4x4->setGeometry(QRect(95, 50, 60, 22));
        checkBox4x4->setChecked(true);
        checkBox6x6 = new QCheckBox(groupBox);
        checkBox6x6->setObjectName(QStringLiteral("checkBox6x6"));
        checkBox6x6->setGeometry(QRect(170, 50, 60, 22));
        checkBox8x8 = new QCheckBox(groupBox);
        checkBox8x8->setObjectName(QStringLiteral("checkBox8x8"));
        checkBox8x8->setGeometry(QRect(240, 50, 60, 22));
        label_2 = new QLabel(groupBox);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(496, 35, 51, 41));
        label_2->setStyleSheet(QStringLiteral("color: gray"));
        label_2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_2->setWordWrap(false);
        groupBox_2 = new QGroupBox(tab_unit_test);
        groupBox_2->setObjectName(QStringLiteral("groupBox_2"));
        groupBox_2->setGeometry(QRect(20, 130, 561, 80));
        label_multiple_windows_2 = new QLabel(groupBox_2);
        label_multiple_windows_2->setObjectName(QStringLiteral("label_multiple_windows_2"));
        label_multiple_windows_2->setGeometry(QRect(0, 0, 561, 80));
        label_multiple_windows_2->setFont(font3);
        label_multiple_windows_2->setFrameShape(QFrame::Box);
        label_multiple_windows_2->setFrameShadow(QFrame::Sunken);
        label_multiple_windows_2->setLineWidth(1);
        label_multiple_windows_2->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        label_multiple_windows_2->setMargin(5);
        label_multiple_windows_2->setIndent(10);
        checkBox256x256 = new QCheckBox(groupBox_2);
        checkBox256x256->setObjectName(QStringLiteral("checkBox256x256"));
        checkBox256x256->setGeometry(QRect(20, 50, 100, 22));
        checkBox256x256->setChecked(false);
        checkBoxCIF = new QCheckBox(groupBox_2);
        checkBoxCIF->setObjectName(QStringLiteral("checkBoxCIF"));
        checkBoxCIF->setGeometry(QRect(120, 50, 55, 22));
        checkBoxCIF->setChecked(true);
        checkBox512x512 = new QCheckBox(groupBox_2);
        checkBox512x512->setObjectName(QStringLiteral("checkBox512x512"));
        checkBox512x512->setGeometry(QRect(175, 50, 95, 22));
        checkBoxD1 = new QCheckBox(groupBox_2);
        checkBoxD1->setObjectName(QStringLiteral("checkBoxD1"));
        checkBoxD1->setGeometry(QRect(275, 50, 50, 22));
        checkBoxD1->setChecked(false);
        checkBox720p = new QCheckBox(groupBox_2);
        checkBox720p->setObjectName(QStringLiteral("checkBox720p"));
        checkBox720p->setGeometry(QRect(335, 50, 60, 22));
        checkBox720p->setChecked(false);
        checkBox1080p = new QCheckBox(groupBox_2);
        checkBox1080p->setObjectName(QStringLiteral("checkBox1080p"));
        checkBox1080p->setGeometry(QRect(410, 50, 75, 22));
        checkBox1080p->setChecked(true);
        label = new QLabel(groupBox_2);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(496, 35, 51, 41));
        label->setStyleSheet(QStringLiteral("color: gray"));
        label->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label->setWordWrap(false);
        pushButtonTextureUpload = new QPushButton(tab_unit_test);
        pushButtonTextureUpload->setObjectName(QStringLiteral("pushButtonTextureUpload"));
        pushButtonTextureUpload->setGeometry(QRect(610, 150, 140, 40));
        pushButtonDifferentResolution = new QPushButton(tab_unit_test);
        pushButtonDifferentResolution->setObjectName(QStringLiteral("pushButtonDifferentResolution"));
        pushButtonDifferentResolution->setGeometry(QRect(610, 250, 140, 40));
        groupBox_3 = new QGroupBox(tab_unit_test);
        groupBox_3->setObjectName(QStringLiteral("groupBox_3"));
        groupBox_3->setGeometry(QRect(20, 230, 561, 80));
        label_multiple_windows_3 = new QLabel(groupBox_3);
        label_multiple_windows_3->setObjectName(QStringLiteral("label_multiple_windows_3"));
        label_multiple_windows_3->setGeometry(QRect(0, 0, 561, 80));
        label_multiple_windows_3->setFont(font3);
        label_multiple_windows_3->setFrameShape(QFrame::Box);
        label_multiple_windows_3->setFrameShadow(QFrame::Sunken);
        label_multiple_windows_3->setLineWidth(1);
        label_multiple_windows_3->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        label_multiple_windows_3->setMargin(5);
        label_multiple_windows_3->setIndent(10);
        checkBox256x256DifferentResolution = new QCheckBox(groupBox_3);
        checkBox256x256DifferentResolution->setObjectName(QStringLiteral("checkBox256x256DifferentResolution"));
        checkBox256x256DifferentResolution->setGeometry(QRect(20, 50, 100, 22));
        checkBox256x256DifferentResolution->setChecked(false);
        checkBoxCIFDifferentResolution = new QCheckBox(groupBox_3);
        checkBoxCIFDifferentResolution->setObjectName(QStringLiteral("checkBoxCIFDifferentResolution"));
        checkBoxCIFDifferentResolution->setGeometry(QRect(120, 50, 55, 22));
        checkBoxCIFDifferentResolution->setChecked(true);
        checkBox512x512DifferentResolution = new QCheckBox(groupBox_3);
        checkBox512x512DifferentResolution->setObjectName(QStringLiteral("checkBox512x512DifferentResolution"));
        checkBox512x512DifferentResolution->setGeometry(QRect(175, 50, 105, 22));
        checkBoxD1DifferentResolution = new QCheckBox(groupBox_3);
        checkBoxD1DifferentResolution->setObjectName(QStringLiteral("checkBoxD1DifferentResolution"));
        checkBoxD1DifferentResolution->setGeometry(QRect(275, 50, 50, 22));
        checkBoxD1DifferentResolution->setChecked(true);
        checkBox720pDifferentResolution = new QCheckBox(groupBox_3);
        checkBox720pDifferentResolution->setObjectName(QStringLiteral("checkBox720pDifferentResolution"));
        checkBox720pDifferentResolution->setGeometry(QRect(335, 50, 70, 22));
        checkBox720pDifferentResolution->setChecked(true);
        checkBox1080pDifferentResolution = new QCheckBox(groupBox_3);
        checkBox1080pDifferentResolution->setObjectName(QStringLiteral("checkBox1080pDifferentResolution"));
        checkBox1080pDifferentResolution->setGeometry(QRect(410, 50, 75, 22));
        checkBox1080pDifferentResolution->setChecked(true);
        label_3 = new QLabel(groupBox_3);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(496, 35, 51, 41));
        label_3->setStyleSheet(QStringLiteral("color: gray"));
        label_3->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_3->setWordWrap(false);
        groupBox_4 = new QGroupBox(tab_unit_test);
        groupBox_4->setObjectName(QStringLiteral("groupBox_4"));
        groupBox_4->setGeometry(QRect(20, 330, 561, 80));
        label_multiple_windows_4 = new QLabel(groupBox_4);
        label_multiple_windows_4->setObjectName(QStringLiteral("label_multiple_windows_4"));
        label_multiple_windows_4->setGeometry(QRect(0, 0, 561, 80));
        label_multiple_windows_4->setFont(font3);
        label_multiple_windows_4->setFrameShape(QFrame::Box);
        label_multiple_windows_4->setFrameShadow(QFrame::Sunken);
        label_multiple_windows_4->setLineWidth(1);
        label_multiple_windows_4->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        label_multiple_windows_4->setMargin(5);
        label_multiple_windows_4->setIndent(10);
        checkBoxRGB32 = new QCheckBox(groupBox_4);
        checkBoxRGB32->setObjectName(QStringLiteral("checkBoxRGB32"));
        checkBoxRGB32->setGeometry(QRect(20, 50, 90, 22));
        checkBoxRGB32->setChecked(true);
        checkBoxYUV420 = new QCheckBox(groupBox_4);
        checkBoxYUV420->setObjectName(QStringLiteral("checkBoxYUV420"));
        checkBoxYUV420->setGeometry(QRect(120, 50, 90, 22));
        checkBoxYUV420->setChecked(true);
        checkBoxYV12 = new QCheckBox(groupBox_4);
        checkBoxYV12->setObjectName(QStringLiteral("checkBoxYV12"));
        checkBoxYV12->setGeometry(QRect(220, 50, 90, 22));
        checkBoxYV12->setChecked(true);
        label_4 = new QLabel(groupBox_4);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(496, 35, 51, 41));
        label_4->setStyleSheet(QStringLiteral("color: gray"));
        label_4->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_4->setWordWrap(false);
        pushButtonDifferentFormat = new QPushButton(tab_unit_test);
        pushButtonDifferentFormat->setObjectName(QStringLiteral("pushButtonDifferentFormat"));
        pushButtonDifferentFormat->setGeometry(QRect(610, 350, 140, 40));
        groupBox_5 = new QGroupBox(tab_unit_test);
        groupBox_5->setObjectName(QStringLiteral("groupBox_5"));
        groupBox_5->setGeometry(QRect(20, 430, 561, 80));
        label_multiple_windows_5 = new QLabel(groupBox_5);
        label_multiple_windows_5->setObjectName(QStringLiteral("label_multiple_windows_5"));
        label_multiple_windows_5->setGeometry(QRect(0, 0, 561, 80));
        label_multiple_windows_5->setFont(font3);
        label_multiple_windows_5->setFrameShape(QFrame::Box);
        label_multiple_windows_5->setFrameShadow(QFrame::Sunken);
        label_multiple_windows_5->setLineWidth(1);
        label_multiple_windows_5->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        label_multiple_windows_5->setMargin(5);
        label_multiple_windows_5->setIndent(10);
        checkBoxSingleProcess = new QCheckBox(groupBox_5);
        checkBoxSingleProcess->setObjectName(QStringLiteral("checkBoxSingleProcess"));
        checkBoxSingleProcess->setGeometry(QRect(20, 50, 210, 22));
        QFont font4;
        font4.setPointSize(10);
        checkBoxSingleProcess->setFont(font4);
        checkBoxSingleProcess->setIconSize(QSize(16, 16));
        checkBoxSingleProcess->setChecked(true);
        checkBoxMultipleProcesses = new QCheckBox(groupBox_5);
        checkBoxMultipleProcesses->setObjectName(QStringLiteral("checkBoxMultipleProcesses"));
        checkBoxMultipleProcesses->setGeometry(QRect(240, 50, 210, 22));
        checkBoxMultipleProcesses->setFont(font4);
        checkBoxMultipleProcesses->setChecked(true);
        label_5 = new QLabel(groupBox_5);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(496, 15, 51, 61));
        label_5->setStyleSheet(QStringLiteral("color: gray"));
        label_5->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_5->setWordWrap(false);
        pushButtonMultipleMonitors = new QPushButton(tab_unit_test);
        pushButtonMultipleMonitors->setObjectName(QStringLiteral("pushButtonMultipleMonitors"));
        pushButtonMultipleMonitors->setGeometry(QRect(610, 450, 140, 40));
        pushButtonRunAll = new QPushButton(tab_unit_test);
        pushButtonRunAll->setObjectName(QStringLiteral("pushButtonRunAll"));
        pushButtonRunAll->setGeometry(QRect(320, 525, 140, 40));
        tabWidget->addTab(tab_unit_test, QString());
        tab_test_configuration = new QWidget();
        tab_test_configuration->setObjectName(QStringLiteral("tab_test_configuration"));
        label_conf_2 = new QLabel(tab_test_configuration);
        label_conf_2->setObjectName(QStringLiteral("label_conf_2"));
        label_conf_2->setGeometry(QRect(240, 20, 141, 40));
        label_conf_2->setFont(font);
        label_conf_2->setFrameShape(QFrame::NoFrame);
        label_conf_2->setFrameShadow(QFrame::Sunken);
        label_conf_2->setLineWidth(1);
        label_conf_2->setTextFormat(Qt::AutoText);
        label_conf_2->setIndent(10);
        pushButtonAdd = new QPushButton(tab_test_configuration);
        pushButtonAdd->setObjectName(QStringLiteral("pushButtonAdd"));
        pushButtonAdd->setGeometry(QRect(570, 90, 31, 31));
        QFont font5;
        font5.setPointSize(12);
        pushButtonAdd->setFont(font5);
        listWidget = new QListWidget(tab_test_configuration);
        listWidget->setObjectName(QStringLiteral("listWidget"));
        listWidget->setGeometry(QRect(580, 140, 171, 351));
        pushButtonRunTestConf = new QPushButton(tab_test_configuration);
        pushButtonRunTestConf->setObjectName(QStringLiteral("pushButtonRunTestConf"));
        pushButtonRunTestConf->setGeometry(QRect(610, 20, 140, 40));
        pushButtonSaveTestConf = new QPushButton(tab_test_configuration);
        pushButtonSaveTestConf->setObjectName(QStringLiteral("pushButtonSaveTestConf"));
        pushButtonSaveTestConf->setGeometry(QRect(600, 520, 140, 40));
        pushButtonDelete = new QPushButton(tab_test_configuration);
        pushButtonDelete->setObjectName(QStringLiteral("pushButtonDelete"));
        pushButtonDelete->setGeometry(QRect(610, 90, 31, 31));
        pushButtonDelete->setFont(font5);
        pushButtonEdit = new QPushButton(tab_test_configuration);
        pushButtonEdit->setObjectName(QStringLiteral("pushButtonEdit"));
        pushButtonEdit->setGeometry(QRect(650, 90, 31, 31));
        pushButtonEdit->setFont(font5);
        pushButtonUp = new QPushButton(tab_test_configuration);
        pushButtonUp->setObjectName(QStringLiteral("pushButtonUp"));
        pushButtonUp->setGeometry(QRect(690, 90, 31, 31));
        pushButtonUp->setFont(font5);
        pushButtonDown = new QPushButton(tab_test_configuration);
        pushButtonDown->setObjectName(QStringLiteral("pushButtonDown"));
        pushButtonDown->setGeometry(QRect(730, 90, 31, 31));
        pushButtonDown->setFont(font5);
        tabWidgetType = new QTabWidget(tab_test_configuration);
        tabWidgetType->setObjectName(QStringLiteral("tabWidgetType"));
        tabWidgetType->setGeometry(QRect(16, 60, 551, 501));
        tab_2 = new QWidget();
        tab_2->setObjectName(QStringLiteral("tab_2"));
        group_mode = new QGroupBox(tab_2);
        group_mode->setObjectName(QStringLiteral("group_mode"));
        group_mode->setGeometry(QRect(8, 10, 531, 51));
        label_mode = new QLabel(group_mode);
        label_mode->setObjectName(QStringLiteral("label_mode"));
        label_mode->setGeometry(QRect(0, 5, 61, 40));
        label_mode->setFont(font1);
        label_mode->setFrameShape(QFrame::NoFrame);
        label_mode->setFrameShadow(QFrame::Sunken);
        label_mode->setLineWidth(1);
        label_mode->setTextFormat(Qt::AutoText);
        label_mode->setIndent(10);
        border_mode = new QLabel(group_mode);
        border_mode->setObjectName(QStringLiteral("border_mode"));
        border_mode->setGeometry(QRect(0, 0, 531, 51));
        border_mode->setFrameShape(QFrame::Box);
        border_mode->setFrameShadow(QFrame::Sunken);
        radios_mode = new QGroupBox(group_mode);
        radios_mode->setObjectName(QStringLiteral("radios_mode"));
        radios_mode->setGeometry(QRect(80, 5, 441, 41));
        radio_mode_video = new QRadioButton(radios_mode);
        radio_mode_video->setObjectName(QStringLiteral("radio_mode_video"));
        radio_mode_video->setGeometry(QRect(40, 10, 131, 22));
        radio_mode_video->setFont(font4);
        radio_mode_video->setChecked(true);
        radio_mode_texture = new QRadioButton(radios_mode);
        radio_mode_texture->setObjectName(QStringLiteral("radio_mode_texture"));
        radio_mode_texture->setGeometry(QRect(170, 10, 141, 22));
        radio_mode_texture->setFont(font4);
        radio_mode_multiple = new QRadioButton(radios_mode);
        radio_mode_multiple->setObjectName(QStringLiteral("radio_mode_multiple"));
        radio_mode_multiple->setGeometry(QRect(310, 10, 131, 22));
        radio_mode_multiple->setFont(font4);
        radio_mode_multiple->setChecked(false);
        group_layout = new QGroupBox(tab_2);
        group_layout->setObjectName(QStringLiteral("group_layout"));
        group_layout->setGeometry(QRect(8, 70, 531, 51));
        border_layout = new QLabel(group_layout);
        border_layout->setObjectName(QStringLiteral("border_layout"));
        border_layout->setGeometry(QRect(0, 0, 531, 51));
        border_layout->setFrameShape(QFrame::Box);
        border_layout->setFrameShadow(QFrame::Sunken);
        label_layout = new QLabel(group_layout);
        label_layout->setObjectName(QStringLiteral("label_layout"));
        label_layout->setGeometry(QRect(2, 5, 80, 40));
        label_layout->setFont(font1);
        label_layout->setFrameShape(QFrame::NoFrame);
        label_layout->setFrameShadow(QFrame::Sunken);
        label_layout->setLineWidth(1);
        label_layout->setTextFormat(Qt::AutoText);
        label_layout->setIndent(10);
        size_layout = new QGroupBox(group_layout);
        size_layout->setObjectName(QStringLiteral("size_layout"));
        size_layout->setGeometry(QRect(180, 4, 121, 41));
        x_layout = new QLabel(size_layout);
        x_layout->setObjectName(QStringLiteral("x_layout"));
        x_layout->setGeometry(QRect(55, 13, 16, 16));
        x_layout->setFont(font2);
        row_spin_test = new QSpinBox(size_layout);
        row_spin_test->setObjectName(QStringLiteral("row_spin_test"));
        row_spin_test->setGeometry(QRect(3, 5, 45, 31));
        row_spin_test->setMinimum(1);
        row_spin_test->setMaximum(8);
        column_spin_test = new QSpinBox(size_layout);
        column_spin_test->setObjectName(QStringLiteral("column_spin_test"));
        column_spin_test->setGeometry(QRect(72, 5, 45, 31));
        column_spin_test->setMinimum(1);
        column_spin_test->setMaximum(8);
        group_pix_test = new QGroupBox(tab_2);
        group_pix_test->setObjectName(QStringLiteral("group_pix_test"));
        group_pix_test->setGeometry(QRect(8, 130, 531, 51));
        label_pix_test = new QLabel(group_pix_test);
        label_pix_test->setObjectName(QStringLiteral("label_pix_test"));
        label_pix_test->setGeometry(QRect(0, 5, 125, 40));
        label_pix_test->setFont(font1);
        label_pix_test->setFrameShape(QFrame::NoFrame);
        label_pix_test->setFrameShadow(QFrame::Sunken);
        label_pix_test->setLineWidth(1);
        label_pix_test->setTextFormat(Qt::AutoText);
        label_pix_test->setIndent(10);
        border_pix_test = new QLabel(group_pix_test);
        border_pix_test->setObjectName(QStringLiteral("border_pix_test"));
        border_pix_test->setGeometry(QRect(0, 0, 531, 51));
        border_pix_test->setFrameShape(QFrame::Box);
        border_pix_test->setFrameShadow(QFrame::Sunken);
        radios_pix_test = new QGroupBox(group_pix_test);
        radios_pix_test->setObjectName(QStringLiteral("radios_pix_test"));
        radios_pix_test->setGeometry(QRect(180, 5, 245, 41));
        radio_rgb32_test = new QRadioButton(radios_pix_test);
        radio_rgb32_test->setObjectName(QStringLiteral("radio_rgb32_test"));
        radio_rgb32_test->setGeometry(QRect(3, 10, 72, 22));
        radio_yuv420_test = new QRadioButton(radios_pix_test);
        radio_yuv420_test->setObjectName(QStringLiteral("radio_yuv420_test"));
        radio_yuv420_test->setGeometry(QRect(84, 10, 82, 22));
        radio_yv12_test = new QRadioButton(radios_pix_test);
        radio_yv12_test->setObjectName(QStringLiteral("radio_yv12_test"));
        radio_yv12_test->setGeometry(QRect(173, 10, 63, 22));
        radio_yv12_test->setChecked(true);
        group_video_test = new QGroupBox(tab_2);
        group_video_test->setObjectName(QStringLiteral("group_video_test"));
        group_video_test->setGeometry(QRect(8, 190, 531, 51));
        label_video_test = new QLabel(group_video_test);
        label_video_test->setObjectName(QStringLiteral("label_video_test"));
        label_video_test->setGeometry(QRect(0, 5, 170, 40));
        label_video_test->setFont(font1);
        label_video_test->setFrameShape(QFrame::NoFrame);
        label_video_test->setFrameShadow(QFrame::Sunken);
        label_video_test->setLineWidth(1);
        label_video_test->setTextFormat(Qt::AutoText);
        label_video_test->setIndent(10);
        border_video_test = new QLabel(group_video_test);
        border_video_test->setObjectName(QStringLiteral("border_video_test"));
        border_video_test->setGeometry(QRect(0, 0, 531, 51));
        border_video_test->setFrameShape(QFrame::Box);
        border_video_test->setFrameShadow(QFrame::Sunken);
        radios_video_test = new QGroupBox(group_video_test);
        radios_video_test->setObjectName(QStringLiteral("radios_video_test"));
        radios_video_test->setGeometry(QRect(160, 5, 361, 41));
        radio_CIF_test = new QRadioButton(radios_video_test);
        radio_CIF_test->setObjectName(QStringLiteral("radio_CIF_test"));
        radio_CIF_test->setGeometry(QRect(80, 10, 50, 22));
        QFont font6;
        font6.setPointSize(8);
        radio_CIF_test->setFont(font6);
        radio_D1_test = new QRadioButton(radios_video_test);
        radio_D1_test->setObjectName(QStringLiteral("radio_D1_test"));
        radio_D1_test->setGeometry(QRect(205, 10, 50, 22));
        radio_D1_test->setFont(font6);
        radio_720p_test = new QRadioButton(radios_video_test);
        radio_720p_test->setObjectName(QStringLiteral("radio_720p_test"));
        radio_720p_test->setGeometry(QRect(250, 10, 60, 22));
        radio_720p_test->setFont(font6);
        radio_1080p_test = new QRadioButton(radios_video_test);
        radio_1080p_test->setObjectName(QStringLiteral("radio_1080p_test"));
        radio_1080p_test->setGeometry(QRect(304, 10, 61, 22));
        radio_1080p_test->setFont(font6);
        radio_1080p_test->setChecked(true);
        radio_512x512_test = new QRadioButton(radios_video_test);
        radio_512x512_test->setObjectName(QStringLiteral("radio_512x512_test"));
        radio_512x512_test->setGeometry(QRect(128, 10, 81, 22));
        radio_512x512_test->setFont(font6);
        radio_256x256_test = new QRadioButton(radios_video_test);
        radio_256x256_test->setObjectName(QStringLiteral("radio_256x256_test"));
        radio_256x256_test->setGeometry(QRect(3, 10, 81, 22));
        radio_256x256_test->setFont(font6);
        group_screen_test = new QGroupBox(tab_2);
        group_screen_test->setObjectName(QStringLiteral("group_screen_test"));
        group_screen_test->setGeometry(QRect(8, 250, 531, 90));
        label_screen_resolution_2 = new QLabel(group_screen_test);
        label_screen_resolution_2->setObjectName(QStringLiteral("label_screen_resolution_2"));
        label_screen_resolution_2->setGeometry(QRect(0, 5, 170, 40));
        label_screen_resolution_2->setFont(font1);
        label_screen_resolution_2->setFrameShape(QFrame::NoFrame);
        label_screen_resolution_2->setFrameShadow(QFrame::Sunken);
        label_screen_resolution_2->setLineWidth(1);
        label_screen_resolution_2->setTextFormat(Qt::AutoText);
        label_screen_resolution_2->setIndent(10);
        border_screen_test = new QLabel(group_screen_test);
        border_screen_test->setObjectName(QStringLiteral("border_screen_test"));
        border_screen_test->setGeometry(QRect(0, 0, 531, 90));
        border_screen_test->setFrameShape(QFrame::Box);
        border_screen_test->setFrameShadow(QFrame::Sunken);
        label_screen_frequncy_2 = new QLabel(group_screen_test);
        label_screen_frequncy_2->setObjectName(QStringLiteral("label_screen_frequncy_2"));
        label_screen_frequncy_2->setGeometry(QRect(55, 45, 105, 40));
        label_screen_frequncy_2->setFont(font1);
        label_screen_frequncy_2->setFrameShape(QFrame::NoFrame);
        label_screen_frequncy_2->setFrameShadow(QFrame::Sunken);
        label_screen_frequncy_2->setLineWidth(1);
        label_screen_frequncy_2->setTextFormat(Qt::AutoText);
        label_screen_frequncy_2->setIndent(10);
        comboBoxTestResolution = new QComboBox(group_screen_test);
        comboBoxTestResolution->setObjectName(QStringLiteral("comboBoxTestResolution"));
        comboBoxTestResolution->setGeometry(QRect(180, 15, 120, 22));
        comboBoxTestFrequency = new QComboBox(group_screen_test);
        comboBoxTestFrequency->setObjectName(QStringLiteral("comboBoxTestFrequency"));
        comboBoxTestFrequency->setGeometry(QRect(180, 55, 69, 22));
        group_process = new QGroupBox(tab_2);
        group_process->setObjectName(QStringLiteral("group_process"));
        group_process->setEnabled(true);
        group_process->setGeometry(QRect(8, 350, 531, 51));
        label_process = new QLabel(group_process);
        label_process->setObjectName(QStringLiteral("label_process"));
        label_process->setGeometry(QRect(0, 5, 151, 40));
        label_process->setFont(font1);
        label_process->setFrameShape(QFrame::NoFrame);
        label_process->setFrameShadow(QFrame::Sunken);
        label_process->setLineWidth(1);
        label_process->setTextFormat(Qt::AutoText);
        label_process->setIndent(10);
        border_process = new QLabel(group_process);
        border_process->setObjectName(QStringLiteral("border_process"));
        border_process->setEnabled(false);
        border_process->setGeometry(QRect(0, 0, 531, 51));
        border_process->setFrameShape(QFrame::Box);
        border_process->setFrameShadow(QFrame::Sunken);
        radios_process = new QGroupBox(group_process);
        radios_process->setObjectName(QStringLiteral("radios_process"));
        radios_process->setGeometry(QRect(140, 5, 381, 41));
        radio_process_single = new QRadioButton(radios_process);
        radio_process_single->setObjectName(QStringLiteral("radio_process_single"));
        radio_process_single->setGeometry(QRect(20, 10, 181, 22));
        radio_process_single->setFont(font6);
        radio_process_single->setChecked(true);
        radio_process_one = new QRadioButton(radios_process);
        radio_process_one->setObjectName(QStringLiteral("radio_process_one"));
        radio_process_one->setGeometry(QRect(200, 10, 181, 22));
        radio_process_one->setFont(font6);
        radio_process_one->setChecked(false);
        group_time = new QGroupBox(tab_2);
        group_time->setObjectName(QStringLiteral("group_time"));
        group_time->setGeometry(QRect(8, 410, 531, 51));
        border_time = new QLabel(group_time);
        border_time->setObjectName(QStringLiteral("border_time"));
        border_time->setGeometry(QRect(0, 0, 531, 51));
        border_time->setFrameShape(QFrame::Box);
        border_time->setFrameShadow(QFrame::Sunken);
        label_time = new QLabel(group_time);
        label_time->setObjectName(QStringLiteral("label_time"));
        label_time->setGeometry(QRect(2, 5, 80, 40));
        label_time->setFont(font1);
        label_time->setFrameShape(QFrame::NoFrame);
        label_time->setFrameShadow(QFrame::Sunken);
        label_time->setLineWidth(1);
        label_time->setTextFormat(Qt::AutoText);
        label_time->setIndent(10);
        size_time = new QGroupBox(group_time);
        size_time->setObjectName(QStringLiteral("size_time"));
        size_time->setGeometry(QRect(180, 4, 121, 41));
        s_time = new QLabel(size_time);
        s_time->setObjectName(QStringLiteral("s_time"));
        s_time->setGeometry(QRect(55, 13, 61, 16));
        s_time->setFont(font2);
        time_spin_test = new QSpinBox(size_time);
        time_spin_test->setObjectName(QStringLiteral("time_spin_test"));
        time_spin_test->setGeometry(QRect(3, 5, 45, 31));
        time_spin_test->setMinimum(10);
        time_spin_test->setMaximum(180);
        time_spin_test->setValue(60);
        tabWidgetType->addTab(tab_2, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QStringLiteral("tab_3"));
        group_lay_decode_2 = new QGroupBox(tab_3);
        group_lay_decode_2->setObjectName(QStringLiteral("group_lay_decode_2"));
        group_lay_decode_2->setGeometry(QRect(8, 10, 531, 51));
        border_lay_decode_2 = new QLabel(group_lay_decode_2);
        border_lay_decode_2->setObjectName(QStringLiteral("border_lay_decode_2"));
        border_lay_decode_2->setGeometry(QRect(0, 0, 531, 51));
        border_lay_decode_2->setFrameShape(QFrame::Box);
        border_lay_decode_2->setFrameShadow(QFrame::Sunken);
        label_lay_decode_2 = new QLabel(group_lay_decode_2);
        label_lay_decode_2->setObjectName(QStringLiteral("label_lay_decode_2"));
        label_lay_decode_2->setGeometry(QRect(2, 5, 80, 40));
        label_lay_decode_2->setFont(font1);
        label_lay_decode_2->setFrameShape(QFrame::NoFrame);
        label_lay_decode_2->setFrameShadow(QFrame::Sunken);
        label_lay_decode_2->setLineWidth(1);
        label_lay_decode_2->setTextFormat(Qt::AutoText);
        label_lay_decode_2->setIndent(10);
        size_lay_decode_2 = new QGroupBox(group_lay_decode_2);
        size_lay_decode_2->setObjectName(QStringLiteral("size_lay_decode_2"));
        size_lay_decode_2->setGeometry(QRect(180, 4, 121, 41));
        x_lay_decode_2 = new QLabel(size_lay_decode_2);
        x_lay_decode_2->setObjectName(QStringLiteral("x_lay_decode_2"));
        x_lay_decode_2->setGeometry(QRect(55, 13, 16, 16));
        x_lay_decode_2->setFont(font2);
        row_spin_decode_test = new QSpinBox(size_lay_decode_2);
        row_spin_decode_test->setObjectName(QStringLiteral("row_spin_decode_test"));
        row_spin_decode_test->setGeometry(QRect(3, 5, 45, 31));
        row_spin_decode_test->setMinimum(1);
        row_spin_decode_test->setMaximum(8);
        column_spin_decode_test = new QSpinBox(size_lay_decode_2);
        column_spin_decode_test->setObjectName(QStringLiteral("column_spin_decode_test"));
        column_spin_decode_test->setGeometry(QRect(72, 5, 45, 31));
        column_spin_decode_test->setMinimum(1);
        column_spin_decode_test->setMaximum(8);
        group_flag_2 = new QGroupBox(tab_3);
        group_flag_2->setObjectName(QStringLiteral("group_flag_2"));
        group_flag_2->setGeometry(QRect(8, 70, 531, 51));
        label_flag_2 = new QLabel(group_flag_2);
        label_flag_2->setObjectName(QStringLiteral("label_flag_2"));
        label_flag_2->setGeometry(QRect(0, 5, 125, 40));
        label_flag_2->setFont(font1);
        label_flag_2->setFrameShape(QFrame::NoFrame);
        label_flag_2->setFrameShadow(QFrame::Sunken);
        label_flag_2->setLineWidth(1);
        label_flag_2->setTextFormat(Qt::AutoText);
        label_flag_2->setIndent(10);
        border_flag_2 = new QLabel(group_flag_2);
        border_flag_2->setObjectName(QStringLiteral("border_flag_2"));
        border_flag_2->setGeometry(QRect(0, 0, 531, 51));
        border_flag_2->setFrameShape(QFrame::Box);
        border_flag_2->setFrameShadow(QFrame::Sunken);
        checkBoxes_flag_3 = new QGroupBox(group_flag_2);
        checkBoxes_flag_3->setObjectName(QStringLiteral("checkBoxes_flag_3"));
        checkBoxes_flag_3->setGeometry(QRect(120, 5, 401, 41));
        checkBoxRenderingVideo_test = new QCheckBox(checkBoxes_flag_3);
        checkBoxRenderingVideo_test->setObjectName(QStringLiteral("checkBoxRenderingVideo_test"));
        checkBoxRenderingVideo_test->setGeometry(QRect(0, 10, 141, 22));
        checkBoxRenderingVideo_test->setChecked(true);
        checkBoxDecodeVideo_test = new QCheckBox(checkBoxes_flag_3);
        checkBoxDecodeVideo_test->setObjectName(QStringLiteral("checkBoxDecodeVideo_test"));
        checkBoxDecodeVideo_test->setGeometry(QRect(150, 10, 121, 22));
        checkBoxDecodeVideo_test->setChecked(true);
        checkBoxDownScaling_test = new QCheckBox(checkBoxes_flag_3);
        checkBoxDownScaling_test->setObjectName(QStringLiteral("checkBoxDownScaling_test"));
        checkBoxDownScaling_test->setGeometry(QRect(280, 10, 121, 22));
        checkBoxDownScaling_test->setChecked(true);
        group_thread_number_2 = new QGroupBox(tab_3);
        group_thread_number_2->setObjectName(QStringLiteral("group_thread_number_2"));
        group_thread_number_2->setGeometry(QRect(8, 130, 531, 51));
        label_thread_number_2 = new QLabel(group_thread_number_2);
        label_thread_number_2->setObjectName(QStringLiteral("label_thread_number_2"));
        label_thread_number_2->setGeometry(QRect(0, 5, 170, 40));
        label_thread_number_2->setFont(font1);
        label_thread_number_2->setFrameShape(QFrame::NoFrame);
        label_thread_number_2->setFrameShadow(QFrame::Sunken);
        label_thread_number_2->setLineWidth(1);
        label_thread_number_2->setTextFormat(Qt::AutoText);
        label_thread_number_2->setIndent(10);
        border_thread_number_2 = new QLabel(group_thread_number_2);
        border_thread_number_2->setObjectName(QStringLiteral("border_thread_number_2"));
        border_thread_number_2->setGeometry(QRect(0, 0, 531, 51));
        border_thread_number_2->setFrameShape(QFrame::Box);
        border_thread_number_2->setFrameShadow(QFrame::Sunken);
        spin_border_2 = new QGroupBox(group_thread_number_2);
        spin_border_2->setObjectName(QStringLiteral("spin_border_2"));
        spin_border_2->setGeometry(QRect(180, 4, 51, 41));
        spin_thread_number_test = new QSpinBox(spin_border_2);
        spin_thread_number_test->setObjectName(QStringLiteral("spin_thread_number_test"));
        spin_thread_number_test->setGeometry(QRect(3, 5, 45, 31));
        spin_thread_number_test->setMinimum(1);
        spin_thread_number_test->setMaximum(8);
        spin_thread_number_test->setValue(4);
        group_timing_control_2 = new QGroupBox(tab_3);
        group_timing_control_2->setObjectName(QStringLiteral("group_timing_control_2"));
        group_timing_control_2->setGeometry(QRect(8, 190, 531, 90));
        label_timing_control_4 = new QLabel(group_timing_control_2);
        label_timing_control_4->setObjectName(QStringLiteral("label_timing_control_4"));
        label_timing_control_4->setGeometry(QRect(0, 5, 170, 40));
        label_timing_control_4->setFont(font1);
        label_timing_control_4->setFrameShape(QFrame::NoFrame);
        label_timing_control_4->setFrameShadow(QFrame::Sunken);
        label_timing_control_4->setLineWidth(1);
        label_timing_control_4->setTextFormat(Qt::AutoText);
        label_timing_control_4->setIndent(10);
        border_timing_control_2 = new QLabel(group_timing_control_2);
        border_timing_control_2->setObjectName(QStringLiteral("border_timing_control_2"));
        border_timing_control_2->setGeometry(QRect(0, 0, 531, 90));
        border_timing_control_2->setFrameShape(QFrame::Box);
        border_timing_control_2->setFrameShadow(QFrame::Sunken);
        label_rate_2 = new QLabel(group_timing_control_2);
        label_rate_2->setObjectName(QStringLiteral("label_rate_2"));
        label_rate_2->setGeometry(QRect(60, 45, 101, 40));
        label_rate_2->setFont(font1);
        label_rate_2->setFrameShape(QFrame::NoFrame);
        label_rate_2->setFrameShadow(QFrame::Sunken);
        label_rate_2->setLineWidth(1);
        label_rate_2->setTextFormat(Qt::AutoText);
        label_rate_2->setIndent(10);
        doubleSpinBox_test = new QDoubleSpinBox(group_timing_control_2);
        doubleSpinBox_test->setObjectName(QStringLiteral("doubleSpinBox_test"));
        doubleSpinBox_test->setGeometry(QRect(180, 54, 69, 22));
        doubleSpinBox_test->setDecimals(1);
        doubleSpinBox_test->setSingleStep(0.1);
        doubleSpinBox_test->setValue(1.3);
        checkBoxes_flag_4 = new QGroupBox(group_timing_control_2);
        checkBoxes_flag_4->setObjectName(QStringLiteral("checkBoxes_flag_4"));
        checkBoxes_flag_4->setGeometry(QRect(180, 5, 121, 41));
        checkBoxTimingControlEnable_test = new QCheckBox(checkBoxes_flag_4);
        checkBoxTimingControlEnable_test->setObjectName(QStringLiteral("checkBoxTimingControlEnable_test"));
        checkBoxTimingControlEnable_test->setGeometry(QRect(10, 10, 81, 22));
        checkBoxTimingControlEnable_test->setChecked(true);
        group_time_2 = new QGroupBox(tab_3);
        group_time_2->setObjectName(QStringLiteral("group_time_2"));
        group_time_2->setGeometry(QRect(10, 290, 531, 51));
        border_time_2 = new QLabel(group_time_2);
        border_time_2->setObjectName(QStringLiteral("border_time_2"));
        border_time_2->setGeometry(QRect(0, 0, 531, 51));
        border_time_2->setFrameShape(QFrame::Box);
        border_time_2->setFrameShadow(QFrame::Sunken);
        label_time_2 = new QLabel(group_time_2);
        label_time_2->setObjectName(QStringLiteral("label_time_2"));
        label_time_2->setGeometry(QRect(2, 5, 80, 40));
        label_time_2->setFont(font1);
        label_time_2->setFrameShape(QFrame::NoFrame);
        label_time_2->setFrameShadow(QFrame::Sunken);
        label_time_2->setLineWidth(1);
        label_time_2->setTextFormat(Qt::AutoText);
        label_time_2->setIndent(10);
        size_time_2 = new QGroupBox(group_time_2);
        size_time_2->setObjectName(QStringLiteral("size_time_2"));
        size_time_2->setGeometry(QRect(180, 4, 121, 41));
        s_time_2 = new QLabel(size_time_2);
        s_time_2->setObjectName(QStringLiteral("s_time_2"));
        s_time_2->setGeometry(QRect(55, 13, 61, 16));
        s_time_2->setFont(font2);
        time_spin_test_decode = new QSpinBox(size_time_2);
        time_spin_test_decode->setObjectName(QStringLiteral("time_spin_test_decode"));
        time_spin_test_decode->setGeometry(QRect(3, 5, 45, 31));
        time_spin_test_decode->setMinimum(10);
        time_spin_test_decode->setMaximum(180);
        time_spin_test_decode->setValue(60);
        tabWidgetType->addTab(tab_3, QString());
        tabWidget->addTab(tab_test_configuration, QString());
        tab_decode_sample = new QWidget();
        tab_decode_sample->setObjectName(QStringLiteral("tab_decode_sample"));
        pushButtonRunDecodeSample = new QPushButton(tab_decode_sample);
        pushButtonRunDecodeSample->setObjectName(QStringLiteral("pushButtonRunDecodeSample"));
        pushButtonRunDecodeSample->setGeometry(QRect(610, 20, 140, 40));
        label_conf_decode = new QLabel(tab_decode_sample);
        label_conf_decode->setObjectName(QStringLiteral("label_conf_decode"));
        label_conf_decode->setGeometry(QRect(240, 20, 141, 40));
        label_conf_decode->setFont(font);
        label_conf_decode->setFrameShape(QFrame::NoFrame);
        label_conf_decode->setFrameShadow(QFrame::Sunken);
        label_conf_decode->setLineWidth(1);
        label_conf_decode->setTextFormat(Qt::AutoText);
        label_conf_decode->setIndent(10);
        group_lay_decode = new QGroupBox(tab_decode_sample);
        group_lay_decode->setObjectName(QStringLiteral("group_lay_decode"));
        group_lay_decode->setGeometry(QRect(30, 85, 710, 51));
        border_lay_decode = new QLabel(group_lay_decode);
        border_lay_decode->setObjectName(QStringLiteral("border_lay_decode"));
        border_lay_decode->setGeometry(QRect(0, 0, 710, 51));
        border_lay_decode->setFrameShape(QFrame::Box);
        border_lay_decode->setFrameShadow(QFrame::Sunken);
        label_lay_decode = new QLabel(group_lay_decode);
        label_lay_decode->setObjectName(QStringLiteral("label_lay_decode"));
        label_lay_decode->setGeometry(QRect(2, 5, 80, 40));
        label_lay_decode->setFont(font1);
        label_lay_decode->setFrameShape(QFrame::NoFrame);
        label_lay_decode->setFrameShadow(QFrame::Sunken);
        label_lay_decode->setLineWidth(1);
        label_lay_decode->setTextFormat(Qt::AutoText);
        label_lay_decode->setIndent(10);
        size_lay_decode = new QGroupBox(group_lay_decode);
        size_lay_decode->setObjectName(QStringLiteral("size_lay_decode"));
        size_lay_decode->setGeometry(QRect(180, 4, 121, 41));
        x_lay_decode = new QLabel(size_lay_decode);
        x_lay_decode->setObjectName(QStringLiteral("x_lay_decode"));
        x_lay_decode->setGeometry(QRect(55, 13, 16, 16));
        x_lay_decode->setFont(font2);
        row_spin_decode = new QSpinBox(size_lay_decode);
        row_spin_decode->setObjectName(QStringLiteral("row_spin_decode"));
        row_spin_decode->setGeometry(QRect(3, 5, 45, 31));
        row_spin_decode->setMinimum(1);
        row_spin_decode->setMaximum(8);
        column_spin_decode = new QSpinBox(size_lay_decode);
        column_spin_decode->setObjectName(QStringLiteral("column_spin_decode"));
        column_spin_decode->setGeometry(QRect(72, 5, 45, 31));
        column_spin_decode->setMinimum(1);
        column_spin_decode->setMaximum(8);
        group_flag = new QGroupBox(tab_decode_sample);
        group_flag->setObjectName(QStringLiteral("group_flag"));
        group_flag->setGeometry(QRect(30, 156, 710, 51));
        label_flag = new QLabel(group_flag);
        label_flag->setObjectName(QStringLiteral("label_flag"));
        label_flag->setGeometry(QRect(0, 5, 125, 40));
        label_flag->setFont(font1);
        label_flag->setFrameShape(QFrame::NoFrame);
        label_flag->setFrameShadow(QFrame::Sunken);
        label_flag->setLineWidth(1);
        label_flag->setTextFormat(Qt::AutoText);
        label_flag->setIndent(10);
        border_flag = new QLabel(group_flag);
        border_flag->setObjectName(QStringLiteral("border_flag"));
        border_flag->setGeometry(QRect(0, 0, 710, 51));
        border_flag->setFrameShape(QFrame::Box);
        border_flag->setFrameShadow(QFrame::Sunken);
        checkBoxes_flag = new QGroupBox(group_flag);
        checkBoxes_flag->setObjectName(QStringLiteral("checkBoxes_flag"));
        checkBoxes_flag->setGeometry(QRect(180, 5, 521, 41));
        checkBoxRenderingVideo = new QCheckBox(checkBoxes_flag);
        checkBoxRenderingVideo->setObjectName(QStringLiteral("checkBoxRenderingVideo"));
        checkBoxRenderingVideo->setGeometry(QRect(10, 10, 171, 22));
        checkBoxRenderingVideo->setChecked(true);
        checkBoxDecodeVideo = new QCheckBox(checkBoxes_flag);
        checkBoxDecodeVideo->setObjectName(QStringLiteral("checkBoxDecodeVideo"));
        checkBoxDecodeVideo->setGeometry(QRect(160, 10, 171, 22));
        checkBoxDecodeVideo->setChecked(true);
        checkBoxDownScaling = new QCheckBox(checkBoxes_flag);
        checkBoxDownScaling->setObjectName(QStringLiteral("checkBoxDownScaling"));
        checkBoxDownScaling->setGeometry(QRect(290, 10, 141, 22));
        checkBoxDownScaling->setChecked(true);
        group_thread_number = new QGroupBox(tab_decode_sample);
        group_thread_number->setObjectName(QStringLiteral("group_thread_number"));
        group_thread_number->setGeometry(QRect(30, 226, 710, 51));
        label_thread_number = new QLabel(group_thread_number);
        label_thread_number->setObjectName(QStringLiteral("label_thread_number"));
        label_thread_number->setGeometry(QRect(0, 5, 170, 40));
        label_thread_number->setFont(font1);
        label_thread_number->setFrameShape(QFrame::NoFrame);
        label_thread_number->setFrameShadow(QFrame::Sunken);
        label_thread_number->setLineWidth(1);
        label_thread_number->setTextFormat(Qt::AutoText);
        label_thread_number->setIndent(10);
        border_thread_number = new QLabel(group_thread_number);
        border_thread_number->setObjectName(QStringLiteral("border_thread_number"));
        border_thread_number->setGeometry(QRect(0, 0, 710, 51));
        border_thread_number->setFrameShape(QFrame::Box);
        border_thread_number->setFrameShadow(QFrame::Sunken);
        spin_border = new QGroupBox(group_thread_number);
        spin_border->setObjectName(QStringLiteral("spin_border"));
        spin_border->setGeometry(QRect(180, 4, 51, 41));
        spin_thread_number = new QSpinBox(spin_border);
        spin_thread_number->setObjectName(QStringLiteral("spin_thread_number"));
        spin_thread_number->setGeometry(QRect(3, 5, 45, 31));
        spin_thread_number->setMinimum(1);
        spin_thread_number->setMaximum(8);
        spin_thread_number->setValue(4);
        group_timing_control = new QGroupBox(tab_decode_sample);
        group_timing_control->setObjectName(QStringLiteral("group_timing_control"));
        group_timing_control->setGeometry(QRect(30, 300, 710, 90));
        label_timing_control_3 = new QLabel(group_timing_control);
        label_timing_control_3->setObjectName(QStringLiteral("label_timing_control_3"));
        label_timing_control_3->setGeometry(QRect(0, 5, 170, 40));
        label_timing_control_3->setFont(font1);
        label_timing_control_3->setFrameShape(QFrame::NoFrame);
        label_timing_control_3->setFrameShadow(QFrame::Sunken);
        label_timing_control_3->setLineWidth(1);
        label_timing_control_3->setTextFormat(Qt::AutoText);
        label_timing_control_3->setIndent(10);
        border_timing_control = new QLabel(group_timing_control);
        border_timing_control->setObjectName(QStringLiteral("border_timing_control"));
        border_timing_control->setGeometry(QRect(0, 0, 710, 90));
        border_timing_control->setFrameShape(QFrame::Box);
        border_timing_control->setFrameShadow(QFrame::Sunken);
        label_rate = new QLabel(group_timing_control);
        label_rate->setObjectName(QStringLiteral("label_rate"));
        label_rate->setGeometry(QRect(60, 45, 101, 40));
        label_rate->setFont(font1);
        label_rate->setFrameShape(QFrame::NoFrame);
        label_rate->setFrameShadow(QFrame::Sunken);
        label_rate->setLineWidth(1);
        label_rate->setTextFormat(Qt::AutoText);
        label_rate->setIndent(10);
        doubleSpinBox = new QDoubleSpinBox(group_timing_control);
        doubleSpinBox->setObjectName(QStringLiteral("doubleSpinBox"));
        doubleSpinBox->setGeometry(QRect(180, 54, 69, 22));
        doubleSpinBox->setDecimals(1);
        doubleSpinBox->setSingleStep(0.1);
        doubleSpinBox->setValue(1.3);
        checkBoxes_flag_2 = new QGroupBox(group_timing_control);
        checkBoxes_flag_2->setObjectName(QStringLiteral("checkBoxes_flag_2"));
        checkBoxes_flag_2->setGeometry(QRect(180, 5, 121, 41));
        checkBoxTimingControlEnable = new QCheckBox(checkBoxes_flag_2);
        checkBoxTimingControlEnable->setObjectName(QStringLiteral("checkBoxTimingControlEnable"));
        checkBoxTimingControlEnable->setGeometry(QRect(10, 10, 81, 22));
        checkBoxTimingControlEnable->setChecked(true);
        pushButtonSaveDecodeSample = new QPushButton(tab_decode_sample);
        pushButtonSaveDecodeSample->setObjectName(QStringLiteral("pushButtonSaveDecodeSample"));
        pushButtonSaveDecodeSample->setGeometry(QRect(320, 510, 140, 40));
        tabWidget->addTab(tab_decode_sample, QString());
        tab = new QWidget();
        tab->setObjectName(QStringLiteral("tab"));
        groupBox_db = new QGroupBox(tab);
        groupBox_db->setObjectName(QStringLiteral("groupBox_db"));
        groupBox_db->setGeometry(QRect(20, 30, 561, 80));
        label_multiple_windows_db = new QLabel(groupBox_db);
        label_multiple_windows_db->setObjectName(QStringLiteral("label_multiple_windows_db"));
        label_multiple_windows_db->setGeometry(QRect(0, 0, 561, 80));
        label_multiple_windows_db->setFont(font3);
        label_multiple_windows_db->setFrameShape(QFrame::Box);
        label_multiple_windows_db->setFrameShadow(QFrame::Sunken);
        label_multiple_windows_db->setLineWidth(1);
        label_multiple_windows_db->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        label_multiple_windows_db->setMargin(5);
        label_multiple_windows_db->setIndent(10);
        checkBox2x2_db = new QCheckBox(groupBox_db);
        checkBox2x2_db->setObjectName(QStringLiteral("checkBox2x2_db"));
        checkBox2x2_db->setGeometry(QRect(100, 50, 60, 22));
        checkBox2x2_db->setChecked(true);
        checkBox4x4_db = new QCheckBox(groupBox_db);
        checkBox4x4_db->setObjectName(QStringLiteral("checkBox4x4_db"));
        checkBox4x4_db->setGeometry(QRect(170, 50, 60, 22));
        checkBox4x4_db->setChecked(true);
        checkBox6x6_db = new QCheckBox(groupBox_db);
        checkBox6x6_db->setObjectName(QStringLiteral("checkBox6x6_db"));
        checkBox6x6_db->setGeometry(QRect(240, 50, 60, 22));
        checkBox8x8_db = new QCheckBox(groupBox_db);
        checkBox8x8_db->setObjectName(QStringLiteral("checkBox8x8_db"));
        checkBox8x8_db->setGeometry(QRect(310, 50, 60, 22));
        label_8 = new QLabel(groupBox_db);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(424, 20, 132, 61));
        label_8->setStyleSheet(QStringLiteral("color: gray"));
        label_8->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_8->setWordWrap(false);
        checkBox1x1_db = new QCheckBox(groupBox_db);
        checkBox1x1_db->setObjectName(QStringLiteral("checkBox1x1_db"));
        checkBox1x1_db->setGeometry(QRect(30, 50, 60, 22));
        pushButtonMultipleWindows_db = new QPushButton(tab);
        pushButtonMultipleWindows_db->setObjectName(QStringLiteral("pushButtonMultipleWindows_db"));
        pushButtonMultipleWindows_db->setGeometry(QRect(610, 50, 140, 40));
        tabWidget->addTab(tab, QString());
        tab_general_options = new QWidget();
        tab_general_options->setObjectName(QStringLiteral("tab_general_options"));
        label_6 = new QLabel(tab_general_options);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(36, 38, 141, 31));
        lineEditExportReport = new QLineEdit(tab_general_options);
        lineEditExportReport->setObjectName(QStringLiteral("lineEditExportReport"));
        lineEditExportReport->setGeometry(QRect(50, 80, 571, 21));
        pushButtonExportReport = new QPushButton(tab_general_options);
        pushButtonExportReport->setObjectName(QStringLiteral("pushButtonExportReport"));
        pushButtonExportReport->setGeometry(QRect(640, 75, 99, 27));
        label_7 = new QLabel(tab_general_options);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(36, 140, 141, 31));
        lineEditSaveScreenshot = new QLineEdit(tab_general_options);
        lineEditSaveScreenshot->setObjectName(QStringLiteral("lineEditSaveScreenshot"));
        lineEditSaveScreenshot->setGeometry(QRect(50, 190, 571, 21));
        pushButtonSaveScreenshot = new QPushButton(tab_general_options);
        pushButtonSaveScreenshot->setObjectName(QStringLiteral("pushButtonSaveScreenshot"));
        pushButtonSaveScreenshot->setGeometry(QRect(640, 185, 99, 27));
        pushButtonSaveGeneralOptions = new QPushButton(tab_general_options);
        pushButtonSaveGeneralOptions->setObjectName(QStringLiteral("pushButtonSaveGeneralOptions"));
        pushButtonSaveGeneralOptions->setGeometry(QRect(320, 510, 140, 40));
        tabWidget->addTab(tab_general_options, QString());
        GLMark->setCentralWidget(centralWidget);

        retranslateUi(GLMark);

        tabWidget->setCurrentIndex(0);
        tabWidgetType->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(GLMark);
    } // setupUi

    void retranslateUi(QMainWindow *GLMark)
    {
        GLMark->setWindowTitle(QApplication::translate("GLMark", "GLMark", 0));
        pushButtonGeneralTest->setText(QApplication::translate("GLMark", "Run", 0));
        label_conf->setText(QApplication::translate("GLMark", "Configuration", 0));
        group_lay->setTitle(QString());
        border_lay->setText(QString());
        label_lay->setText(QApplication::translate("GLMark", "Layout", 0));
        size_lay->setTitle(QString());
        x_lay->setText(QApplication::translate("GLMark", "x", 0));
        group_pix->setTitle(QString());
        label_pix->setText(QApplication::translate("GLMark", "Pixel Format", 0));
        border_pix->setText(QString());
        radios_pix->setTitle(QString());
        radio_rgb32->setText(QApplication::translate("GLMark", "RGB32", 0));
        radio_yuv420->setText(QApplication::translate("GLMark", "YUV420", 0));
        radio_yv12->setText(QApplication::translate("GLMark", "YV12", 0));
        group_video->setTitle(QString());
        label_video->setText(QApplication::translate("GLMark", "Video Resolution", 0));
        border_video->setText(QString());
        radios_video->setTitle(QString());
        radio_CIF->setText(QApplication::translate("GLMark", "CIF", 0));
        radio_D1->setText(QApplication::translate("GLMark", "D1", 0));
        radio_720p->setText(QApplication::translate("GLMark", "720p", 0));
        radio_1080p->setText(QApplication::translate("GLMark", "1080p", 0));
        group_screen->setTitle(QString());
        label_screen_resolution->setText(QApplication::translate("GLMark", "Screen Resolution", 0));
        border_screen->setText(QString());
        label_screen_frequncy->setText(QApplication::translate("GLMark", "Frequency", 0));
        pushButtonSaveRenderingSample->setText(QApplication::translate("GLMark", "Save", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_general_test), QApplication::translate("GLMark", "Rendering Sample", 0));
        pushButtonMultipleWindows->setText(QApplication::translate("GLMark", "Run", 0));
        groupBox->setTitle(QString());
        label_multiple_windows->setText(QApplication::translate("GLMark", "Estimate Performance of Video Rendering in Multiple Windows", 0));
        checkBox2x2->setText(QApplication::translate("GLMark", "2 x 2", 0));
        checkBox4x4->setText(QApplication::translate("GLMark", "4 x 4", 0));
        checkBox6x6->setText(QApplication::translate("GLMark", "6 x 6", 0));
        checkBox8x8->setText(QApplication::translate("GLMark", "8 x 8", 0));
        label_2->setText(QApplication::translate("GLMark", "YV12\n"
"1080p", 0));
        groupBox_2->setTitle(QString());
        label_multiple_windows_2->setText(QApplication::translate("GLMark", "Estimate Performance of Texture Upload Bandwitdh in Different Resolution", 0));
        checkBox256x256->setText(QApplication::translate("GLMark", "256 x 256", 0));
        checkBoxCIF->setText(QApplication::translate("GLMark", "CIF", 0));
        checkBox512x512->setText(QApplication::translate("GLMark", "512 x 512", 0));
        checkBoxD1->setText(QApplication::translate("GLMark", "D1", 0));
        checkBox720p->setText(QApplication::translate("GLMark", "720p", 0));
        checkBox1080p->setText(QApplication::translate("GLMark", "1080p", 0));
        label->setText(QApplication::translate("GLMark", "YV12", 0));
        pushButtonTextureUpload->setText(QApplication::translate("GLMark", "Run", 0));
        pushButtonDifferentResolution->setText(QApplication::translate("GLMark", "Run", 0));
        groupBox_3->setTitle(QString());
        label_multiple_windows_3->setText(QApplication::translate("GLMark", "Estimate Performance of Video Rendering in Different Resolution", 0));
        checkBox256x256DifferentResolution->setText(QApplication::translate("GLMark", "256 x 256", 0));
        checkBoxCIFDifferentResolution->setText(QApplication::translate("GLMark", "CIF", 0));
        checkBox512x512DifferentResolution->setText(QApplication::translate("GLMark", "512 x 512", 0));
        checkBoxD1DifferentResolution->setText(QApplication::translate("GLMark", "D1", 0));
        checkBox720pDifferentResolution->setText(QApplication::translate("GLMark", "720p", 0));
        checkBox1080pDifferentResolution->setText(QApplication::translate("GLMark", "1080p", 0));
        label_3->setText(QApplication::translate("GLMark", "4 x 4\n"
"YV12", 0));
        groupBox_4->setTitle(QString());
        label_multiple_windows_4->setText(QApplication::translate("GLMark", "Estimate Performance of Video Rendering in Different Format", 0));
        checkBoxRGB32->setText(QApplication::translate("GLMark", "RGB32", 0));
        checkBoxYUV420->setText(QApplication::translate("GLMark", "YUV420", 0));
        checkBoxYV12->setText(QApplication::translate("GLMark", "YV12", 0));
        label_4->setText(QApplication::translate("GLMark", "4 x 4\n"
"1080p", 0));
        pushButtonDifferentFormat->setText(QApplication::translate("GLMark", "Run", 0));
        groupBox_5->setTitle(QString());
        label_multiple_windows_5->setText(QApplication::translate("GLMark", "Estimate Performance of Video Rendering in Multiple Monitors", 0));
        checkBoxSingleProcess->setText(QApplication::translate("GLMark", "Single Process for All Monitors", 0));
        checkBoxMultipleProcesses->setText(QApplication::translate("GLMark", "One Process for Each Monitor", 0));
        label_5->setText(QApplication::translate("GLMark", "4 x 4\n"
"YV12\n"
"1080p", 0));
        pushButtonMultipleMonitors->setText(QApplication::translate("GLMark", "Run", 0));
        pushButtonRunAll->setText(QApplication::translate("GLMark", "Run All", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_unit_test), QApplication::translate("GLMark", "Rendering Benchmark", 0));
        label_conf_2->setText(QApplication::translate("GLMark", "Configuration", 0));
        pushButtonAdd->setText(QApplication::translate("GLMark", "+", 0));
        pushButtonRunTestConf->setText(QApplication::translate("GLMark", "Run", 0));
        pushButtonSaveTestConf->setText(QApplication::translate("GLMark", "Save", 0));
        pushButtonDelete->setText(QApplication::translate("GLMark", "-", 0));
        pushButtonEdit->setText(QApplication::translate("GLMark", "e", 0));
        pushButtonUp->setText(QApplication::translate("GLMark", "^", 0));
        pushButtonDown->setText(QApplication::translate("GLMark", "v", 0));
        group_mode->setTitle(QString());
        label_mode->setText(QApplication::translate("GLMark", "Mode", 0));
        border_mode->setText(QString());
        radios_mode->setTitle(QString());
        radio_mode_video->setText(QApplication::translate("GLMark", "Video Rendering", 0));
        radio_mode_texture->setText(QApplication::translate("GLMark", "Texture Uploading", 0));
        radio_mode_multiple->setText(QApplication::translate("GLMark", "Multiple Monitors", 0));
        group_layout->setTitle(QString());
        border_layout->setText(QString());
        label_layout->setText(QApplication::translate("GLMark", "Layout", 0));
        size_layout->setTitle(QString());
        x_layout->setText(QApplication::translate("GLMark", "x", 0));
        group_pix_test->setTitle(QString());
        label_pix_test->setText(QApplication::translate("GLMark", "Pixel Format", 0));
        border_pix_test->setText(QString());
        radios_pix_test->setTitle(QString());
        radio_rgb32_test->setText(QApplication::translate("GLMark", "RGB32", 0));
        radio_yuv420_test->setText(QApplication::translate("GLMark", "YUV420", 0));
        radio_yv12_test->setText(QApplication::translate("GLMark", "YV12", 0));
        group_video_test->setTitle(QString());
        label_video_test->setText(QApplication::translate("GLMark", "Video Resolution", 0));
        border_video_test->setText(QString());
        radios_video_test->setTitle(QString());
        radio_CIF_test->setText(QApplication::translate("GLMark", "CIF", 0));
        radio_D1_test->setText(QApplication::translate("GLMark", "D1", 0));
        radio_720p_test->setText(QApplication::translate("GLMark", "720p", 0));
        radio_1080p_test->setText(QApplication::translate("GLMark", "1080p", 0));
        radio_512x512_test->setText(QApplication::translate("GLMark", "512 x 512", 0));
        radio_256x256_test->setText(QApplication::translate("GLMark", "256 x 256", 0));
        group_screen_test->setTitle(QString());
        label_screen_resolution_2->setText(QApplication::translate("GLMark", "Screen Resolution", 0));
        border_screen_test->setText(QString());
        label_screen_frequncy_2->setText(QApplication::translate("GLMark", "Frequency", 0));
        group_process->setTitle(QString());
        label_process->setText(QApplication::translate("GLMark", "Process Setting", 0));
        border_process->setText(QString());
        radios_process->setTitle(QString());
        radio_process_single->setText(QApplication::translate("GLMark", "Single Process for All Monitors", 0));
        radio_process_one->setText(QApplication::translate("GLMark", "One Process for Each Monitor", 0));
        group_time->setTitle(QString());
        border_time->setText(QString());
        label_time->setText(QApplication::translate("GLMark", "Time", 0));
        size_time->setTitle(QString());
        s_time->setText(QApplication::translate("GLMark", "seconds", 0));
        tabWidgetType->setTabText(tabWidgetType->indexOf(tab_2), QApplication::translate("GLMark", "Rendering", 0));
        group_lay_decode_2->setTitle(QString());
        border_lay_decode_2->setText(QString());
        label_lay_decode_2->setText(QApplication::translate("GLMark", "Layout", 0));
        size_lay_decode_2->setTitle(QString());
        x_lay_decode_2->setText(QApplication::translate("GLMark", "x", 0));
        group_flag_2->setTitle(QString());
        label_flag_2->setText(QApplication::translate("GLMark", "Flag", 0));
        border_flag_2->setText(QString());
        checkBoxes_flag_3->setTitle(QString());
        checkBoxRenderingVideo_test->setText(QApplication::translate("GLMark", "Rendering Video", 0));
        checkBoxDecodeVideo_test->setText(QApplication::translate("GLMark", "Decode Video", 0));
        checkBoxDownScaling_test->setText(QApplication::translate("GLMark", "Down Scaling", 0));
        group_thread_number_2->setTitle(QString());
        label_thread_number_2->setText(QApplication::translate("GLMark", "Thread Number", 0));
        border_thread_number_2->setText(QString());
        spin_border_2->setTitle(QString());
        group_timing_control_2->setTitle(QString());
        label_timing_control_4->setText(QApplication::translate("GLMark", "Timing Control", 0));
        border_timing_control_2->setText(QString());
        label_rate_2->setText(QApplication::translate("GLMark", "Rate", 0));
        checkBoxes_flag_4->setTitle(QString());
        checkBoxTimingControlEnable_test->setText(QApplication::translate("GLMark", "Enable", 0));
        group_time_2->setTitle(QString());
        border_time_2->setText(QString());
        label_time_2->setText(QApplication::translate("GLMark", "Time", 0));
        size_time_2->setTitle(QString());
        s_time_2->setText(QApplication::translate("GLMark", "seconds", 0));
        tabWidgetType->setTabText(tabWidgetType->indexOf(tab_3), QApplication::translate("GLMark", "Decode", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_test_configuration), QApplication::translate("GLMark", "Test Configuration", 0));
        pushButtonRunDecodeSample->setText(QApplication::translate("GLMark", "Run", 0));
        label_conf_decode->setText(QApplication::translate("GLMark", "Configuration", 0));
        group_lay_decode->setTitle(QString());
        border_lay_decode->setText(QString());
        label_lay_decode->setText(QApplication::translate("GLMark", "Layout", 0));
        size_lay_decode->setTitle(QString());
        x_lay_decode->setText(QApplication::translate("GLMark", "x", 0));
        group_flag->setTitle(QString());
        label_flag->setText(QApplication::translate("GLMark", "Flag", 0));
        border_flag->setText(QString());
        checkBoxes_flag->setTitle(QString());
        checkBoxRenderingVideo->setText(QApplication::translate("GLMark", "Rendering Video", 0));
        checkBoxDecodeVideo->setText(QApplication::translate("GLMark", "Decode Video", 0));
        checkBoxDownScaling->setText(QApplication::translate("GLMark", "Down Scaling", 0));
        group_thread_number->setTitle(QString());
        label_thread_number->setText(QApplication::translate("GLMark", "Thread Number", 0));
        border_thread_number->setText(QString());
        spin_border->setTitle(QString());
        group_timing_control->setTitle(QString());
        label_timing_control_3->setText(QApplication::translate("GLMark", "Timing Control", 0));
        border_timing_control->setText(QString());
        label_rate->setText(QApplication::translate("GLMark", "Rate", 0));
        checkBoxes_flag_2->setTitle(QString());
        checkBoxTimingControlEnable->setText(QApplication::translate("GLMark", "Enable", 0));
        pushButtonSaveDecodeSample->setText(QApplication::translate("GLMark", "Save", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_decode_sample), QApplication::translate("GLMark", "Decode Sample", 0));
        groupBox_db->setTitle(QString());
        label_multiple_windows_db->setText(QApplication::translate("GLMark", "Estimate Performance of Video Decoding in Multiple Windows", 0));
        checkBox2x2_db->setText(QApplication::translate("GLMark", "2 x 2", 0));
        checkBox4x4_db->setText(QApplication::translate("GLMark", "4 x 4", 0));
        checkBox6x6_db->setText(QApplication::translate("GLMark", "6 x 6", 0));
        checkBox8x8_db->setText(QApplication::translate("GLMark", "8 x 8", 0));
        label_8->setText(QApplication::translate("GLMark", "disable renderer\n"
"4 threads\n"
"enable hw decode", 0));
        checkBox1x1_db->setText(QApplication::translate("GLMark", "1 x 1", 0));
        pushButtonMultipleWindows_db->setText(QApplication::translate("GLMark", "Run", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("GLMark", "Decode Benchmark", 0));
        label_6->setText(QApplication::translate("GLMark", "Export Report in:", 0));
        pushButtonExportReport->setText(QApplication::translate("GLMark", "Browse..", 0));
        label_7->setText(QApplication::translate("GLMark", "Save Screenshot in:", 0));
        pushButtonSaveScreenshot->setText(QApplication::translate("GLMark", "Browse..", 0));
        pushButtonSaveGeneralOptions->setText(QApplication::translate("GLMark", "Save", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_general_options), QApplication::translate("GLMark", "General Options", 0));
    } // retranslateUi

};

namespace Ui {
    class GLMark: public Ui_GLMark {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_GLMARK_H
